#!/usr/bin/env bash

export SOURCE_DIR
SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

(
  cd "$SOURCE_DIR" || exit

  export DOCKER_TAG
  DOCKER_TAG="rafops/paperkey:latest-$(uname -m)"

  export DOCKER_ENTRYPOINT
  DOCKER_ENTRYPOINT="$1"
  shift
  [[ -z "$DOCKER_ENTRYPOINT" ]] && DOCKER_ENTRYPOINT="bash"

  docker pull "$DOCKER_TAG" 2>/dev/null || docker build -t "$DOCKER_TAG" .

  docker run -it --rm \
   --entrypoint "$DOCKER_ENTRYPOINT" \
   --network none \
   --user paperkey \
   --mount type=tmpfs,destination=/home/paperkey/tmp \
    -v "$HOME/.gnupg:/home/paperkey/.gnupg" \
    -v "$SOURCE_DIR/data:/home/paperkey/data" \
    "$DOCKER_TAG" "$@"
)

